spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    password: 123456
    username: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印
  type-aliases-package: com.tyl.vueblog.entity   #取别名
  mapper-locations: classpath:mapper/*.xml   #配置xml文件是 ，文件放置的地方

tyl:
  jwt:
    #加密钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    #设置token的有效时长
    expire: 604800
    header: Authorization
server:
  port: 8081

